#pragma once

/**
 * @file CarlaBridge.h
 * @brief Native C++ bridge between the JavaCPP JNI layer and the
 *        CARLA C++ client SDK.
 *
 * @details
 * Every type declared in this header maps 1:1 to a Java class
 * generated by JavaCPP in `org.carla.javacpp.binding.CarlaNative`.
 * The C++ side owns the actual CARLA objects (`carla::client::*`)
 * and exposes a small, value-friendly façade that the JNI layer
 * can call from Java without sharing any CARLA headers with the
 * generated Java code.
 *
 * Lifetime contract:
 *  - Each `*Handle` class is heap-allocated by the C++ bridge
 *    and is owned by the Java side through a `Pointer` returned
 *    by JavaCPP.
 *  - The corresponding `Delete*Handle` free function must be
 *    called exactly once to release the handle and any CARLA
 *    resources it owns. The Java wrappers in
 *    `org.carla.javacpp.api` enforce this through the
 *    `NativeHandle` base class.
 */

#include <cstddef>
#include <cstdint>
#include <condition_variable>
#include <memory>
#include <mutex>
#include <string>
#include <vector>

#include <carla/Memory.h>

namespace carla {
    namespace client {
        class Actor;
        class ActorList;
        class BlueprintLibrary;
        class ActorBlueprint;
        class Client;
        class Map;
        class Sensor;
        class Waypoint;
        class World;
    } // namespace client
    namespace geom {
        class Transform;
    } // namespace geom
} // namespace carla

namespace carlajava {

/**
 * @brief Plain-old-data 3D point used as a JNI argument type.
 *
 * Coordinates are in meters, in the CARLA world frame:
 * `+x` is forward, `+y` is right, `+z` is up.
 */
struct LocationValue {
  double x; ///< Forward distance, in meters.
  double y; ///< Right distance, in meters.
  double z; ///< Up distance, in meters.
};

/**
 * @brief Plain-old-data rotation used as a JNI argument type.
 *
 * All angles are in degrees, applied in the CARLA order
 * (pitch, then yaw, then roll).
 */
struct RotationValue {
  double pitch; ///< Rotation around the right axis, in degrees.
  double yaw;   ///< Rotation around the up axis, in degrees.
  double roll;  ///< Rotation around the forward axis, in degrees.
};

/**
 * @brief Pair of a location and a rotation.
 */
struct TransformValue {
  LocationValue location; ///< World location component.
  RotationValue rotation; ///< Orientation component.
};

/**
 * @brief Plain-old-data snapshot of a world's simulation
 *        settings.
 */
struct WorldSettingsValue {
  bool synchronous_mode;        ///< Enable server-driven synchronous mode.
  bool no_rendering_mode;       ///< Skip rendering on the server.
  bool has_fixed_delta_seconds; ///< Whether @ref fixed_delta_seconds is meaningful.
  double fixed_delta_seconds;   ///< Optional fixed delta in seconds.
};

/**
 * @brief Plain-old-data snapshot of a world's weather
 *        parameters.
 *
 * Mirrors the fields of `carla::rpc::WeatherParameters`.
 */
struct WeatherParametersValue {
  float cloudiness;              ///< Cloudiness in `[0, 100]`.
  float precipitation;           ///< Precipitation in `[0, 100]`.
  float precipitation_deposits;  ///< Wet deposits in `[0, 100]`.
  float wind_intensity;          ///< Wind intensity in `[0, 100]`.
  float sun_azimuth_angle;       ///< Sun azimuth in degrees.
  float sun_altitude_angle;      ///< Sun altitude in degrees.
  float fog_density;             ///< Fog density in `[0, 100]`.
  float fog_distance;            ///< Fog start distance in meters.
  float fog_falloff;             ///< Fog falloff in `[0, 100]`.
  float wetness;                 ///< Ground wetness in `[0, 100]`.
  float scattering_intensity;    ///< Scattering intensity in `[0, 100]`.
  float mie_scattering_scale;    ///< Mie scattering scale.
  float rayleigh_scattering_scale; ///< Rayleigh scattering scale.
  float dust_storm;              ///< Dust storm intensity in `[0, 100]`.
};

/**
 * @brief Owning handle to a `carla::client::Client`.
 *
 * The Java wrapper `org.carla.javacpp.api.Client` holds a
 * pointer to an instance of this class and calls
 * `DeleteClientHandle` to release it.
 */
class ClientHandle {
public:
  /**
   * @brief Connects to a running CARLA server.
   *
   * @param host server host (for example `"localhost"`).
   * @param port server TCP port (default CARLA port is `2000`).
   */
  ClientHandle(const std::string &host, uint16_t port);
  ~ClientHandle();

  /**
   * @brief Sets the network timeout used for every RPC.
   *
   * @param timeout_millis timeout in milliseconds.
   */
  void SetTimeoutMillis(long long timeout_millis);

  /**
   * @brief Returns the world currently loaded on the server.
   *
   * @return a heap-allocated `WorldHandle` owned by the caller.
   *         The Java side releases it through
   *         `DeleteWorldHandle`.
   */
  class WorldHandle *GetWorld() const;

  /**
   * @brief Starts a server-side recording.
   *
   * @param name           target file name on the server.
   * @param additional_data write additional per-frame data.
   * @return the absolute path written by the server.
   */
  std::string StartRecorder(const std::string &name, bool additional_data) const;

  /// Stops the current server-side recording, if any.
  void StopRecorder() const;

  /**
   * @brief Returns textual information about a recording.
   *
   * @param name     recording file name.
   * @param show_all include every frame in the output.
   * @return a multi-line text description of the recording.
   */
  std::string ShowRecorderFileInfo(const std::string &name, bool show_all) const;

  /**
   * @brief Returns collision events recorded in a file.
   *
   * @param name  recording file name.
   * @param type1 first actor-type filter.
   * @param type2 second actor-type filter.
   * @return a multi-line text listing of matching events.
   */
  std::string ShowRecorderCollisions(const std::string &name, char type1, char type2) const;

  /**
   * @brief Lists actors that were blocked during a recording.
   *
   * @param name        recording file name.
   * @param min_time    minimum blocked duration, in seconds.
   * @param min_distance minimum radius the actor must stay within,
   *                     in meters.
   * @return a multi-line text listing of blocked actors.
   */
  std::string ShowRecorderActorsBlocked(const std::string &name,
                                        double min_time,
                                        double min_distance) const;

  /**
   * @brief Replays a recording on the server.
   *
   * @param name          recording file name.
   * @param start         start time, in seconds.
   * @param duration      replay duration, in seconds. `0.0` means
   *                      full replay.
   * @param follow_id     actor id to follow with the spectator,
   *                      or `0` to leave the spectator alone.
   * @param replay_sensors whether to replay sensor data.
   * @param offset        extra transform applied to every replayed
   *                      actor.
   * @return a textual status message from the server.
   */
  std::string ReplayFile(const std::string &name,
                         double start,
                         double duration,
                         uint32_t follow_id,
                         bool replay_sensors,
                         const TransformValue &offset) const;

  /**
   * @brief Stops an ongoing replay.
   *
   * @param keep_actors when `true`, actors created by the
   *                    replayer are kept alive.
   */
  void StopReplayer(bool keep_actors) const;

  /// Sets the time factor of an ongoing replay.
  void SetReplayerTimeFactor(double time_factor) const;

  /// Configures whether the replayer should ignore the hero.
  void SetReplayerIgnoreHero(bool ignore_hero) const;

  /// Configures whether the replayer should ignore the spectator.
  void SetReplayerIgnoreSpectator(bool ignore_spectator) const;

private:
  std::unique_ptr<carla::client::Client> client_;
};

/**
 * @brief Owning handle to a `carla::client::World`.
 */
class WorldHandle {
public:
  /**
   * @brief Wraps a world value object.
   *
   * The handle takes ownership of the supplied world.
   */
  explicit WorldHandle(carla::client::World world);
  ~WorldHandle();

  /// @return the currently loaded map name.
  std::string GetMapName() const;

  /// @return a heap-allocated `MapHandle` owned by the caller.
  class MapHandle *GetMap() const;

  /// @return a heap-allocated `BlueprintLibraryHandle` owned by the caller.
  class BlueprintLibraryHandle *GetBlueprintLibrary() const;

  /// @return a heap-allocated `ActorListHandle` owned by the caller.
  class ActorListHandle *GetActors() const;

  /// @return a heap-allocated `TransformListHandle` owned by the caller.
  class TransformListHandle *GetSpawnPoints() const;

  /// @return the active simulation settings.
  WorldSettingsValue GetSettings() const;

  /**
   * @brief Pushes new simulation settings to the server.
   *
   * @param settings        new settings to apply.
   * @param timeout_millis  maximum time to wait for
   *                        acknowledgement, in milliseconds.
   * @return the frame id of the acknowledged change.
   */
  uint64_t ApplySettings(const WorldSettingsValue &settings, long long timeout_millis) const;

  /**
   * @brief Advances the simulation by a single step.
   *
   * Only meaningful when the world is in synchronous mode.
   *
   * @param timeout_millis  maximum time to wait for
   *                        acknowledgement, in milliseconds.
   * @return the frame id of the acknowledged tick.
   */
  uint64_t Tick(long long timeout_millis) const;

  /// @return the active weather parameters.
  WeatherParametersValue GetWeather() const;

  /// Replaces the current weather with the given parameters.
  void SetWeather(const WeatherParametersValue &weather) const;

  /**
   * @brief Spawns an actor from a blueprint at a transform.
   *
   * @return a heap-allocated `ActorHandle` owned by the caller.
   * @throws std::runtime_error if the server rejects the spawn.
   */
  class ActorHandle *SpawnActor(const class BlueprintHandle &blueprint,
                                const TransformValue &transform) const;

  /**
   * @brief Attempts to spawn an actor, returning `nullptr` on
   *        failure instead of throwing.
   *
   * @return a heap-allocated `ActorHandle` owned by the caller,
   *         or `nullptr` when the server refused the spawn.
   */
  class ActorHandle *TrySpawnActor(const class BlueprintHandle &blueprint,
                                   const TransformValue &transform) const;

  /**
   * @brief Spawns an RGB camera sensor attached to `parent`.
   *
   * @return a heap-allocated `CameraSensorHandle` owned by the
   *         caller.
   */
  class CameraSensorHandle *SpawnRgbCamera(const class ActorHandle &parent,
                                           const TransformValue &transform,
                                           int width,
                                           int height,
                                           double fov) const;

  /**
   * @brief Spawns a collision sensor attached to `parent`.
   *
   * @return a heap-allocated `CollisionSensorHandle` owned by
   *         the caller.
   */
  class CollisionSensorHandle *SpawnCollisionSensor(const class ActorHandle &parent,
                                                    const TransformValue &transform) const;

  /**
   * @brief Spawns a LIDAR sensor attached to `parent`.
   *
   * @return a heap-allocated `LidarSensorHandle` owned by the
   *         caller.
   */
  class LidarSensorHandle *SpawnLidar(const class ActorHandle &parent,
                                      const TransformValue &transform,
                                      int channels,
                                      double range,
                                      int points_per_second,
                                      double rotation_frequency,
                                      double upper_fov,
                                      double lower_fov) const;

private:
  std::unique_ptr<carla::client::World> world_;
};

/**
 * @brief Owning handle to a `carla::client::Map`.
 */
class MapHandle {
public:
  /**
   * @brief Wraps a shared CARLA map.
   *
   * The handle keeps a `carla::SharedPtr` to the underlying map
   * so the same map can be shared with other CARLA objects.
   */
  explicit MapHandle(carla::SharedPtr<carla::client::Map> map);
  ~MapHandle();

  /// @return the map name.
  std::string GetName() const;

  /**
   * @brief Returns the waypoint closest to a given location.
   *
   * @param location       world location to project.
   * @param project_to_road when `true`, the location is projected
   *                        onto the nearest lane.
   * @return a heap-allocated `WaypointHandle` owned by the
   *         caller, or `nullptr` if no waypoint was found.
   */
  class WaypointHandle *GetWaypoint(const LocationValue &location,
                                    bool project_to_road) const;

  /**
   * @brief Generates a regularly-spaced grid of waypoints.
   *
   * @param distance step size in meters.
   * @return a heap-allocated `WaypointListHandle` owned by the
   *         caller.
   */
  class WaypointListHandle *GenerateWaypoints(double distance) const;

private:
  carla::SharedPtr<carla::client::Map> map_;
};

/**
 * @brief Owning handle to a `carla::client::Waypoint`.
 */
class WaypointHandle {
public:
  explicit WaypointHandle(carla::SharedPtr<carla::client::Waypoint> waypoint);
  ~WaypointHandle();

  /// @return the unique waypoint id.
  uint64_t GetId() const;
  /// @return the id of the road this waypoint belongs to.
  int32_t GetRoadId() const;
  /// @return the id of the road section this waypoint belongs to.
  int32_t GetSectionId() const;
  /// @return the lane id (positive: forward, negative: reverse).
  int32_t GetLaneId() const;
  /// @return the arc length from the section start, in meters.
  double GetDistance() const;
  /// @return the waypoint's world transform.
  TransformValue GetTransform() const;
  /// @return whether the waypoint lies inside a junction.
  bool IsJunction() const;
  /// @return the lane width at this waypoint, in meters.
  double GetLaneWidth() const;

  /**
   * @brief Walks the lane forward by the given distance.
   *
   * @return a heap-allocated `WaypointListHandle` owned by the
   *         caller, possibly empty.
   */
  class WaypointListHandle *Next(double distance) const;

  /**
   * @brief Walks the lane backward by the given distance.
   *
   * @return a heap-allocated `WaypointListHandle` owned by the
   *         caller, possibly empty.
   */
  class WaypointListHandle *Previous(double distance) const;

  /// @return the waypoint on the right adjacent lane, or `nullptr`.
  class WaypointHandle *GetRight() const;
  /// @return the waypoint on the left adjacent lane, or `nullptr`.
  class WaypointHandle *GetLeft() const;

private:
  carla::SharedPtr<carla::client::Waypoint> waypoint_;
};

/**
 * @brief Owning handle to a list of waypoints.
 */
class WaypointListHandle {
public:
  explicit WaypointListHandle(std::vector<carla::SharedPtr<carla::client::Waypoint>> waypoints);
  ~WaypointListHandle();

  /// @return the number of waypoints in the list.
  size_t Size() const;

  /**
   * @brief Returns the waypoint at the given index.
   *
   * @return a heap-allocated `WaypointHandle` owned by the
   *         caller, or `nullptr` if the index is out of range.
   */
  WaypointHandle *Get(size_t index) const;

private:
  std::vector<carla::SharedPtr<carla::client::Waypoint>> waypoints_;
};

/**
 * @brief Owning handle to a `carla::client::ActorBlueprint`.
 */
class BlueprintHandle {
public:
  explicit BlueprintHandle(carla::client::ActorBlueprint blueprint);
  ~BlueprintHandle();

  /// @return the blueprint type id.
  std::string GetId() const;

  /**
   * @brief Sets an attribute on the blueprint.
   *
   * @param key   attribute name.
   * @param value new value as a string (parsed server-side
   *              according to the attribute's declared type).
   */
  void SetAttribute(const std::string &key, const std::string &value);

  /// @return a const reference to the underlying CARLA blueprint.
  const carla::client::ActorBlueprint &Get() const;

private:
  std::unique_ptr<carla::client::ActorBlueprint> blueprint_;
};

/**
 * @brief Owning handle to a `carla::client::BlueprintLibrary`.
 */
class BlueprintLibraryHandle {
public:
  explicit BlueprintLibraryHandle(carla::SharedPtr<carla::client::BlueprintLibrary> library);
  ~BlueprintLibraryHandle();

  /**
   * @brief Returns blueprints whose id matches a wildcard
   *        pattern.
   *
   * @return a heap-allocated `BlueprintListHandle` owned by the
   *         caller.
   */
  class BlueprintListHandle *Filter(const std::string &pattern) const;

  /**
   * @brief Looks up a blueprint by its exact id.
   *
   * @return a heap-allocated `BlueprintHandle` owned by the
   *         caller.
   * @throws std::runtime_error if no blueprint matches the id.
   */
  class BlueprintHandle *Find(const std::string &id) const;

private:
  carla::SharedPtr<carla::client::BlueprintLibrary> library_;
};

/**
 * @brief Owning handle to a list of blueprint handles.
 */
class BlueprintListHandle {
public:
  explicit BlueprintListHandle(std::vector<BlueprintHandle *> blueprints);
  ~BlueprintListHandle();

  /// @return the number of blueprints in the list.
  size_t Size() const;

  /// @return a borrowed reference to the blueprint at @p index.
  BlueprintHandle *Get(size_t index) const;

private:
  std::vector<BlueprintHandle *> blueprints_;
};

/**
 * @brief Owning handle to a `carla::client::Actor`.
 */
class ActorHandle {
public:
  explicit ActorHandle(carla::SharedPtr<carla::client::Actor> actor);
  ~ActorHandle();

  /// @return the unique actor id assigned by the server.
  uint32_t GetId() const;
  /// @return the blueprint type id used to spawn this actor.
  std::string GetTypeId() const;
  /// @return the actor's current world transform.
  TransformValue GetTransform() const;
  /// @return `true` if the server confirmed the destruction.
  bool Destroy() const;
  /// Toggles autopilot, talking to the traffic manager on @p traffic_manager_port.
  void SetAutopilot(bool enabled, uint16_t traffic_manager_port);
  /// Applies a low-level vehicle control command.
  void ApplyVehicleControl(float throttle,
                           float steer,
                           float brake,
                           bool hand_brake,
                           bool reverse);
  /// @return a const reference to the underlying CARLA actor.
  const carla::SharedPtr<carla::client::Actor> &Get() const;

private:
  carla::SharedPtr<carla::client::Actor> actor_;
};

/**
 * @brief Owning handle to a list of transforms.
 */
class TransformListHandle {
public:
  explicit TransformListHandle(std::vector<TransformValue> transforms);
  ~TransformListHandle();

  /// @return the number of transforms in the list.
  size_t Size() const;
  /// @return the transform at the given index.
  TransformValue Get(size_t index) const;

private:
  std::vector<TransformValue> transforms_;
};

/**
 * @brief Owning handle to a single BGRA camera frame.
 */
class CameraImageHandle {
public:
  /**
   * @brief Wraps a frame produced by the CARLA camera sensor.
   *
   * @param frame     simulation frame id.
   * @param timestamp simulation timestamp, in seconds.
   * @param width     image width, in pixels.
   * @param height    image height, in pixels.
   * @param bgra      tightly packed BGRA pixel buffer of length
   *                  `width * height * 4`.
   */
  CameraImageHandle(size_t frame, double timestamp, uint32_t width, uint32_t height,
                    std::vector<uint8_t> bgra);
  ~CameraImageHandle();

  /// @return the frame id of this image.
  size_t GetFrame() const;
  /// @return the simulation timestamp, in seconds.
  double GetTimestamp() const;
  /// @return the image width, in pixels.
  uint32_t GetWidth() const;
  /// @return the image height, in pixels.
  uint32_t GetHeight() const;
  /// @return the size of the underlying pixel buffer in bytes.
  size_t Size() const;
  /// @return a pointer to the first byte of the BGRA buffer.
  const uint8_t *Data() const;

private:
  size_t frame_;
  double timestamp_;
  uint32_t width_;
  uint32_t height_;
  std::vector<uint8_t> bgra_;
};

/**
 * @brief Owning handle to a CARLA RGB camera sensor.
 *
 * The handle owns the underlying sensor and the latest cached
 * frame. A listener thread is **not** used; JavaCPP polls the
 * sensor with @ref PollImage.
 */
class CameraSensorHandle {
public:
  explicit CameraSensorHandle(carla::SharedPtr<carla::client::Actor> actor);
  ~CameraSensorHandle();

  /**
   * @brief Waits for the next frame and returns it.
   *
   * @param timeout_millis maximum time to wait, in milliseconds.
   * @return a heap-allocated `CameraImageHandle` owned by the
   *         caller, or `nullptr` if the timeout elapsed.
   */
  CameraImageHandle *PollImage(long long timeout_millis);

  /// @return the unique sensor id assigned by the server.
  uint32_t GetId() const;
  /// @return `true` if the server confirmed the destruction.
  bool Destroy() const;

private:
  struct FrameData {
    size_t frame;
    double timestamp;
    uint32_t width;
    uint32_t height;
    std::vector<uint8_t> bgra;
  };

  carla::SharedPtr<carla::client::Actor> actor_;
  carla::SharedPtr<carla::client::Sensor> sensor_;
  std::mutex mutex_;
  std::condition_variable condition_;
  bool has_frame_ = false;
  FrameData latest_frame_{};
};

/**
 * @brief Owning handle to a single collision event.
 */
class CollisionEventHandle {
public:
  /**
   * @brief Wraps a collision event produced by the sensor.
   *
   * @param frame              simulation frame id.
   * @param timestamp          simulation timestamp, in seconds.
   * @param actor_id           id of the parent actor.
   * @param other_actor_id     id of the other actor.
   * @param other_actor_type_id blueprint type id of the other actor.
   * @param normal_impulse_x   `x` component of the normal impulse.
   * @param normal_impulse_y   `y` component of the normal impulse.
   * @param normal_impulse_z   `z` component of the normal impulse.
   */
  CollisionEventHandle(size_t frame,
                       double timestamp,
                       uint32_t actor_id,
                       uint32_t other_actor_id,
                       std::string other_actor_type_id,
                       double normal_impulse_x,
                       double normal_impulse_y,
                       double normal_impulse_z);
  ~CollisionEventHandle();

  size_t GetFrame() const;
  double GetTimestamp() const;
  uint32_t GetActorId() const;
  uint32_t GetOtherActorId() const;
  std::string GetOtherActorTypeId() const;
  double GetNormalImpulseX() const;
  double GetNormalImpulseY() const;
  double GetNormalImpulseZ() const;

private:
  size_t frame_;
  double timestamp_;
  uint32_t actor_id_;
  uint32_t other_actor_id_;
  std::string other_actor_type_id_;
  double normal_impulse_x_;
  double normal_impulse_y_;
  double normal_impulse_z_;
};

/**
 * @brief Owning handle to a CARLA collision sensor.
 */
class CollisionSensorHandle {
public:
  explicit CollisionSensorHandle(carla::SharedPtr<carla::client::Actor> actor);
  ~CollisionSensorHandle();

  /**
   * @brief Waits for the next collision event and returns it.
   *
   * @param timeout_millis maximum time to wait, in milliseconds.
   * @return a heap-allocated `CollisionEventHandle` owned by the
   *         caller, or `nullptr` if the timeout elapsed.
   */
  CollisionEventHandle *PollEvent(long long timeout_millis);

  /// @return the unique sensor id assigned by the server.
  uint32_t GetId() const;
  /// @return `true` if the server confirmed the destruction.
  bool Destroy() const;

private:
  struct EventData {
    size_t frame;
    double timestamp;
    uint32_t actor_id;
    uint32_t other_actor_id;
    std::string other_actor_type_id;
    double normal_impulse_x;
    double normal_impulse_y;
    double normal_impulse_z;
  };

  carla::SharedPtr<carla::client::Actor> actor_;
  carla::SharedPtr<carla::client::Sensor> sensor_;
  std::mutex mutex_;
  std::condition_variable condition_;
  bool has_event_ = false;
  EventData latest_event_{};
};

/**
 * @brief Owning handle to a single LIDAR point cloud.
 */
class LidarMeasurementHandle {
public:
  /**
   * @brief Wraps a LIDAR point cloud.
   *
   * @param frame            simulation frame id.
   * @param timestamp        simulation timestamp, in seconds.
   * @param horizontal_angle current sensor rotation, in radians.
   * @param channel_count    number of vertical layers in the cloud.
   * @param points           tightly packed point buffer of length
   *                         `4 * point_count`, in `(x, y, z, intensity)`
   *                         order.
   */
  LidarMeasurementHandle(size_t frame,
                         double timestamp,
                         float horizontal_angle,
                         uint32_t channel_count,
                         std::vector<float> points);
  ~LidarMeasurementHandle();

  size_t GetFrame() const;
  double GetTimestamp() const;
  float GetHorizontalAngle() const;
  uint32_t GetChannelCount() const;

  /// @return the number of points in the cloud.
  size_t PointCount() const;

  /// @return the size of the underlying point buffer in floats.
  size_t Size() const;
  /// @return a pointer to the first float of the point buffer.
  const float *Data() const;

private:
  size_t frame_;
  double timestamp_;
  float horizontal_angle_;
  uint32_t channel_count_;
  std::vector<float> points_;
};

/**
 * @brief Owning handle to a CARLA LIDAR sensor.
 */
class LidarSensorHandle {
public:
  explicit LidarSensorHandle(carla::SharedPtr<carla::client::Actor> actor);
  ~LidarSensorHandle();

  /**
   * @brief Waits for the next LIDAR measurement and returns it.
   *
   * @param timeout_millis maximum time to wait, in milliseconds.
   * @return a heap-allocated `LidarMeasurementHandle` owned by
   *         the caller, or `nullptr` if the timeout elapsed.
   */
  LidarMeasurementHandle *PollMeasurement(long long timeout_millis);

  /// @return the unique sensor id assigned by the server.
  uint32_t GetId() const;
  /// @return `true` if the server confirmed the destruction.
  bool Destroy() const;

private:
  struct MeasurementData {
    size_t frame;
    double timestamp;
    float horizontal_angle;
    uint32_t channel_count;
    std::vector<float> points;
  };

  carla::SharedPtr<carla::client::Actor> actor_;
  carla::SharedPtr<carla::client::Sensor> sensor_;
  std::mutex mutex_;
  std::condition_variable condition_;
  bool has_measurement_ = false;
  MeasurementData latest_measurement_{};
};

/**
 * @brief Owning handle to a list of actors.
 */
class ActorListHandle {
public:
  explicit ActorListHandle(std::vector<carla::SharedPtr<carla::client::Actor>> actors);
  ~ActorListHandle();

  /// @return the number of actors in the list.
  size_t Size() const;

  /// @return a borrowed reference to the actor at @p index.
  ActorHandle *Get(size_t index) const;

private:
  std::vector<carla::SharedPtr<carla::client::Actor>> actors_;
};

/// @name Lifetime management
/// Each free function releases a single handle and any CARLA
/// resources it owns. The function must be called exactly once
/// per handle returned by the constructors above.
/// @{
void DeleteClientHandle(ClientHandle *handle);
void DeleteWorldHandle(WorldHandle *handle);
void DeleteMapHandle(MapHandle *handle);
void DeleteWaypointHandle(WaypointHandle *handle);
void DeleteWaypointListHandle(WaypointListHandle *handle);
void DeleteBlueprintLibraryHandle(BlueprintLibraryHandle *handle);
void DeleteBlueprintListHandle(BlueprintListHandle *handle);
void DeleteBlueprintHandle(BlueprintHandle *handle);
void DeleteActorHandle(ActorHandle *handle);
void DeleteActorListHandle(ActorListHandle *handle);
void DeleteTransformListHandle(TransformListHandle *handle);
void DeleteCameraSensorHandle(CameraSensorHandle *handle);
void DeleteCameraImageHandle(CameraImageHandle *handle);
void DeleteCollisionSensorHandle(CollisionSensorHandle *handle);
void DeleteCollisionEventHandle(CollisionEventHandle *handle);
void DeleteLidarSensorHandle(LidarSensorHandle *handle);
void DeleteLidarMeasurementHandle(LidarMeasurementHandle *handle);
/// @}

} // namespace carlajava
