/**
 * High-level Java facade for the CARLA simulator.
 *
 * <p>This package contains the user-facing API: the
 * {@link org.carla.javacpp.api.Client} entry point, the
 * {@link org.carla.javacpp.api.World} it returns, the value types
 * used to describe poses and weather, and the sensor and actor
 * wrappers that map onto native CARLA objects.</p>
 *
 * <p>The classes here are pure Java wrappers over the JNI layer
 * generated by JavaCPP in the
 * <code>org.carla.javacpp.binding</code> package. They manage the
 * lifetime of the underlying native handles through
 * {@link org.carla.javacpp.api.NativeHandle}, and surface CARLA
 * errors as {@link org.carla.javacpp.api.CarlaException}.</p>
 *
 * <p>Typical entry points are:</p>
 * <ul>
 *     <li>{@link org.carla.javacpp.api.Client} — connect to a
 *         running CARLA server;</li>
 *     <li>{@link org.carla.javacpp.api.World} — interact with the
 *         simulation, spawn actors, drive the simulation
 *         forward;</li>
 *     <li>{@link org.carla.javacpp.api.Map} and
 *         {@link org.carla.javacpp.api.Waypoint} — read the road
 *         network.</li>
 * </ul>
 */
package org.carla.javacpp.api;
